### PR TITLE
[#9] Display parameters passed to PIT to trace issue

### PR DESCRIPTION
**Pull request by szpak**

### CODE REVIEW

**Comment by magneticflux-** [comment]
Sorry, I misunderstood what you had in mind. Does this give you the information you wanted?

**Comment by szpak** [comment]
It will ensure that the parameters are passed from my plugin to PIT correctly (and eliminate issue with that from the circle of suspects).

**Comment by magneticflux-** [comment]
Ah, that makes sense. It seems as though the parameter is passed correctly. Are you certain your plugin correctly send a `BUILD FAILED` signal back to the Gradle task every time?

**Comment by szpak** [comment]
See: https://github.com/szpak/gradle-pitest-plugin/issues/57#issuecomment-285945375

**Comment by magneticflux-** [comment]
Fixed, see szpak/gradle-pitest-plugin#57

**Pull request closed without merging**
